/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package i18n_message_file_generator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
